In [ ]:
# Workflow of ML---->
# Data Ingestion----> Data Cleaning and Preprocessing----> Select ML model---->
# Model Training----> Model prediction----> Calculate Performance of Model.

In [ ]:
# 1. Data cleaning and preprocessing---->
# Data----> x_train, x_test, y_train, y_test
# Machine(x_train, y_train)
# 1+1 = 2
# 2+2 = 4
# 3+2 = 5
# 4+6 = 10

# Machine (5+7) ----???? ----> predict = 13
# 5+7 = x_test
# 12 = y_test
# 13 ----> y_pred
# Machine (y_pred, y_test)

In [ ]:
# How can we create data dividation?

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [ ]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
x = df.drop(columns=['has_covid'])  # Input or Independent data
x.shape

(100, 5)

In [ ]:
y = df['has_covid']   # Target or Dependent data
y.shape

(100,)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,
                                                    y,
                                                    test_size = 0.2,
                                                    random_state = 42)

In [ ]:
print('Total data shape : ',df.shape)
print('-----------------------------------')
print('Input data shape:',x.shape)
print('x_train data shape:',x_train.shape)
print('x_test data shape:',x_test.shape)
print('-----------------------------------')
print('Target data shape:',y.shape)
print('y_train data shape:',y_train.shape)
print('y_test data shape:',y_test.shape)
print('-----------------------------------')

Total data shape :  (100, 6)
-----------------------------------
Input data shape: (100, 5)
x_train data shape: (80, 5)
x_test data shape: (20, 5)
-----------------------------------
Target data shape: (100,)
y_train data shape: (80,)
y_test data shape: (20,)
-----------------------------------

In [ ]:
df2 = pd.read_csv('/content/Customer_Call.xlsx - Call List.csv')
df2.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True

In [ ]:
df2.isnull().sum()

CustomerID           0
First_Name           0
Last_Name            1
Phone_Number         2
Address              0
Paying Customer      0
Do_Not_Contact       4
Not_Useful_Column    0
dtype: int64

In [ ]:
df2['Do_Not_Contact'].value_counts()

Do_Not_Contact
No     9
N      4
Yes    3
Y      1
Name: count, dtype: int64

In [ ]:
df2['Do_Not_Contact'] = df2['Do_Not_Contact'].fillna('No')

In [ ]:
df2 = df2.dropna()

In [ ]:
df2.isnull().sum()

CustomerID           0
First_Name           0
Last_Name            0
Phone_Number         0
Address              0
Paying Customer      0
Do_Not_Contact       0
Not_Useful_Column    0
dtype: int64

In [ ]:
x = df2.drop(columns = ['Paying Customer'])
x.shape

(18, 7)

In [ ]:
y = df2['Paying Customer']
y.shape

(18,)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,
                                                    y,
                                                    test_size=0.2,
                                                    random_state=45)

In [ ]:
print('Total data shape : ',df2.shape)
print('-----------------------------------')
print('Input data shape:',x.shape)
print('x_train data shape:',x_train.shape)
print('x_test data shape:',x_test.shape)
print('-----------------------------------')
print('Target data shape:',y.shape)
print('y_train data shape:',y_train.shape)
print('y_test data shape:',y_test.shape)
print('-----------------------------------')

Total data shape :  (18, 8)
-----------------------------------
Input data shape: (18, 7)
x_train data shape: (14, 7)
x_test data shape: (4, 7)
-----------------------------------
Target data shape: (18,)
y_train data shape: (14,)
y_test data shape: (4,)
-----------------------------------

In [ ]:
df3 = pd.read_csv('/content/titanic - titanic.csv')
df3.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [ ]:
df3.shape

(418, 12)

In [ ]:
df3.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
df3['Cabin'].value_counts()

Cabin
B57 B59 B63 B66    3
B45                2
C23 C25 C27        2
C78                2
C31                2
                  ..
B41                1
C7                 1
D40                1
D38                1
C105               1
Name: count, Length: 76, dtype: int64

In [ ]:
df3['Cabin'] = df3['Cabin'].fillna('B57 B59 B63 B66	')

In [ ]:
df3['Age'] = df3['Age'].fillna(df3['Age'].mean())

In [ ]:
df3['Fare'] = df3['Fare'].fillna(df3['Fare'].mean())

In [ ]:
df3.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [ ]:
x = df3.drop(columns = ['Survived'])

In [ ]:
y = df3['Survived']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,
                                                    y,
                                                    test_size = 0.2,
                                                    random_state = 50)

In [ ]:
print('Total data shape : ',df3.shape)
print('-----------------------------------')
print('Input data shape:',x.shape)
print('x_train data shape:',x_train.shape)
print('x_test data shape:',x_test.shape)
print('-----------------------------------')
print('Target data shape:',y.shape)
print('y_train data shape:',y_train.shape)
print('y_test data shape:',y_test.shape)
print('-----------------------------------')

Total data shape :  (418, 12)
-----------------------------------
Input data shape: (418, 11)
x_train data shape: (334, 11)
x_test data shape: (84, 11)
-----------------------------------
Target data shape: (418,)
y_train data shape: (334,)
y_test data shape: (84,)
-----------------------------------

In [ ]:
df = pd.read_csv('/content/Attrition - Attrition.csv')
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [ ]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [ ]:
x = df.drop(columns=['Attrition'])

In [ ]:
y = df['Attrition']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,
                                                    y,
                                                    test_size=0.2,
                                                    random_state = 50)

In [ ]:
print('Total data shape : ',df.shape)
print('-----------------------------------')
print('Input data shape:',x.shape)
print('x_train data shape:',x_train.shape)
print('x_test data shape:',x_test.shape)
print('-----------------------------------')
print('Target data shape:',y.shape)
print('y_train data shape:',y_train.shape)
print('y_test data shape:',y_test.shape)
print('-----------------------------------')

Total data shape :  (1470, 35)
-----------------------------------
Input data shape: (1470, 34)
x_train data shape: (1176, 34)
x_test data shape: (294, 34)
-----------------------------------
Target data shape: (1470,)
y_train data shape: (1176,)
y_test data shape: (294,)
-----------------------------------

In [ ]:
# Normal Distribution ---->
# from central tendency(mean, median, mode) ----> left and right side equal data points.
# Identification
# mean = 0, standard deviation = 1

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/covid_toy.csv')

In [ ]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
df = df.dropna()

In [ ]:
df = df.drop(columns=['cough','city'])

In [ ]:
df.head(2)

   age gender  fever has_covid
0   60   Male  103.0        No
1   27   Male  100.0       Yes

In [ ]:
df['gender'] = df['gender'].map({'Male':0,'Female':1})
df['has_covid'] = df['has_covid'].map({'Yes':1,'No':0})

In [ ]:
df.head(2)

   age  gender  fever  has_covid
0   60       0  103.0          0
1   27       0  100.0          1

In [ ]:
x = df.drop(columns=['has_covid'])
y = df['has_covid']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,
                                                    y,
                                                    test_size=0.2,
                                                    random_state=50)

In [ ]:
np.round(x_train.describe(),2)

         age  gender   fever
count  72.00   72.00   72.00
mean   43.10    0.62  100.88
std    24.34    0.49    1.99
min     5.00    0.00   98.00
25%    21.50    0.00   99.00
50%    46.50    1.00  101.00
75%    65.00    1.00  102.25
max    83.00    1.00  104.00

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
x_train_sc = sc.fit_transform(x_train)  # Fit means learn the parameter and transform means apply on that data

In [ ]:
x_train_new = pd.DataFrame(x_train_sc,columns=x_train.columns)

In [ ]:
np.round(x_train_new.describe(),2)

         age  gender  fever
count  72.00   72.00  72.00
mean    0.00    0.00  -0.00
std     1.01    1.01   1.01
min    -1.58   -1.29  -1.45
25%    -0.89   -1.29  -0.95
50%     0.14    0.77   0.06
75%     0.91    0.77   0.69
max     1.65    0.77   1.58

In [ ]:
import seaborn as sns

In [ ]:
df = sns.load_dataset('tips')

In [ ]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [ ]:
df['sex'] = df['sex'].map({'Male':1,'Female':0})
df['time'] = df['time'].map({'Dinner':1,'Lunch':0})
df['smoker'] = df['smoker'].map({'Yes':1,'No':0})

In [ ]:
df = df.drop(columns=['day'])

In [ ]:
df.head(2)

   total_bill   tip sex smoker time  size
0       16.99  1.01   0      0    1     2
1       10.34  1.66   1      0    1     3

In [ ]:
x = df.drop(columns=['total_bill'])
y = df['total_bill']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,
                                                     y,
                                                     test_size=0.2,
                                                     random_state=50)

In [ ]:
np.round(x_train.describe(),2)

          tip    size
count  195.00  195.00
mean     2.94    2.56
std      1.37    0.97
min      1.00    1.00
25%      2.00    2.00
50%      2.74    2.00
75%      3.50    3.00
max     10.00    6.00

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
x_train_sc = sc.fit_transform(x_train)

In [ ]:
x_train_new = pd.DataFrame(x_train_sc,columns=x_train.columns)

In [ ]:
np.round(x_train_new.describe(),2)

          tip     sex  smoker    time    size
count  195.00  195.00  195.00  195.00  195.00
mean    -0.00    0.00   -0.00    0.00   -0.00
std      1.00    1.00    1.00    1.00    1.00
min     -1.42   -1.38   -0.74   -1.64   -1.62
25%     -0.69   -1.38   -0.74   -1.64   -0.58
50%     -0.15    0.72   -0.74    0.61   -0.58
75%      0.41    0.72    1.35    0.61    0.45
max      5.15    0.72    1.35    0.61    3.56

In [ ]:
# NormaliZation ----> Min - 0, Max = 1

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/Churn_Modelling - Churn_Modelling.csv')

In [ ]:
df.head(2)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0

In [ ]:
df = df.drop(columns=['Surname','Geography'])

In [ ]:
df['Gender'] = df['Gender'].map({'Male':1,'Female':0})

In [ ]:
x  = df.drop(columns=['Exited'])
y = df['Exited']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,
                                                    y,
                                                    test_size = 0.2,
                                                    random_state=50)

In [ ]:
np.round(x_train.describe(),2)

,RowNumber,CustomerId,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
count,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00
mean,4997.57,15690743.49,649.26,0.55,38.81,5.01,76422.52,1.53,0.70,0.52,100128.71
std,2883.47,72012.87,97.04,0.50,10.45,2.89,62456.95,0.58,0.46,0.50,57604.84
min,2.00,15565701.00,350.00,0.00,18.00,0.00,0.00,1.00,0.00,0.00,11.58
25%,2509.75,15628052.75,582.00,0.00,32.00,2.00,0.00,1.00,0.00,0.00,50871.10
50%,4999.50,15690667.00,651.00,1.00,37.00,5.00,97250.34,1.00,1.00,1.00,100238.11
75%,7502.75,15753554.00,717.00,1.00,44.00,7.00,127417.33,2.00,1.00,1.00,149602.95
max,10000.00,15815660.00,850.00,1.00,92.00,10.00,250898.09,4.00,1.00,1.00,199992.48

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
mn = MinMaxScaler()

In [ ]:
x_train_mn = mn.fit_transform(x_train)

In [ ]:
x_train_new = pd.DataFrame(x_train_mn,columns=x_train.columns)

In [ ]:
np.round(x_train_new.describe(),2)

,RowNumber,CustomerId,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
count,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00
mean,0.50,0.50,0.60,0.55,0.28,0.50,0.30,0.18,0.70,0.52,0.50
std,0.29,0.29,0.19,0.50,0.14,0.29,0.25,0.19,0.46,0.50,0.29
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.25,0.25,0.46,0.00,0.19,0.20,0.00,0.00,0.00,0.00,0.25
50%,0.50,0.50,0.60,1.00,0.26,0.50,0.39,0.00,1.00,1.00,0.50
75%,0.75,0.75,0.73,1.00,0.35,0.70,0.51,0.33,1.00,1.00,0.75
max,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00

In [ ]:
df = pd.read_csv('/content/toyota - toyota.csv')

In [ ]:
df.head(2)

  model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0  GT86  2016  16000       Manual    24089   Petrol  265  36.2         2.0
1  GT86  2017  15995       Manual    18615   Petrol  145  36.2         2.0

In [ ]:
df = df.drop(columns=['model','year'])

In [ ]:
df['fuelType'].value_counts()

fuelType
Petrol    4087
Hybrid    2043
Diesel     503
Other      105
Name: count, dtype: int64

In [ ]:
df['transmission']=df['transmission'].map({'Manual':1,'Automatic':2,'Semi-Auto':3,'Other':4})
df['fuelType']=df['fuelType'].map({'Petrol':1,'Hybrid':2,'Diesel':3,'Other':4})

In [ ]:
df.head(2)

   price  transmission  mileage  fuelType  tax   mpg  engineSize
0  16000             1    24089         1  265  36.2         2.0
1  15995             1    18615         1  145  36.2         2.0

In [ ]:
x = df.drop(columns=['price'])
y = df['price']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,
                                                     y,
                                                     test_size=0.2,
                                                     random_state=50)

In [ ]:
np.round(x_train.describe(),2)

       transmission    mileage  fuelType      tax      mpg  engineSize
count       5390.00    5390.00    5390.0  5390.00  5390.00     5390.00
mean           1.47   22836.02       1.5    94.85    63.09        1.47
std            0.57   19104.25       0.7    73.57    16.09        0.43
min            1.00       2.00       1.0     0.00     2.80        0.00
25%            1.00    9449.50       1.0     0.00    55.40        1.00
50%            1.00   18506.00       1.0   135.00    61.40        1.50
75%            2.00   30998.25       2.0   145.00    70.60        1.80
max            4.00  174419.00       4.0   565.00   235.00        4.20

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
mn = MinMaxScaler()

In [ ]:
x_train_mn = mn.fit_transform(x_train)

In [ ]:
x_train_new = pd.DataFrame(x_train_mn,columns=x_train.columns)

In [ ]:
np.round(x_train_new.describe(),2)

       transmission  mileage  fuelType      tax      mpg  engineSize
count       5390.00  5390.00   5390.00  5390.00  5390.00     5390.00
mean           0.16     0.13      0.17     0.17     0.26        0.35
std            0.19     0.11      0.23     0.13     0.07        0.10
min            0.00     0.00      0.00     0.00     0.00        0.00
25%            0.00     0.05      0.00     0.00     0.23        0.24
50%            0.00     0.11      0.00     0.24     0.25        0.36
75%            0.33     0.18      0.33     0.26     0.29        0.43
max            1.00     1.00      1.00     1.00     1.00        1.00

In [ ]:
df = pd.read_csv('/content/covid_toy.csv')
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
df = df.drop(columns=['city'])

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
has_covid     0
dtype: int64

In [ ]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [ ]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
has_covid    0
dtype: int64

In [ ]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [ ]:
df['gender'] = df['gender'].map({'Male':1,'Female':0})
df['cough'] = df['cough'].map({'Mild':1,'Strong':2})
df['has_covid']=df['has_covid'].map({'Yes':1,'No':0})

In [ ]:
covid = df

In [ ]:
df.to_csv('covid.csv')

In [ ]:
x  = df.drop(columns=['has_covid'])
y = df['has_covid']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,
                                               y,
                                               test_size=0.2,
                                               random_state=50)

In [ ]:
np.round(x_train.describe(),2)

         age  gender   fever  cough
count  80.00   80.00   80.00  80.00
mean   43.58    0.44  100.84   1.40
std    25.83    0.50    1.95   0.49
min     5.00    0.00   98.00   1.00
25%    20.00    0.00   99.00   1.00
50%    42.00    0.00  100.84   1.00
75%    66.50    1.00  102.00   2.00
max    84.00    1.00  104.00   2.00

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
mn = MinMaxScaler()

In [ ]:
x_train_mn = mn.fit_transform(x_train)

In [ ]:
x_train_new = pd.DataFrame(x_train_mn,columns=x_train.columns)

In [ ]:
np.round(x_train_new.describe(),2)

         age  gender  fever  cough
count  80.00   80.00  80.00  80.00
mean    0.49    0.44   0.47   0.40
std     0.33    0.50   0.32   0.49
min     0.00    0.00   0.00   0.00
25%     0.19    0.00   0.17   0.00
50%     0.47    0.00   0.47   0.00
75%     0.78    1.00   0.67   1.00
max     1.00    1.00   1.00   1.00

In [ ]:
import seaborn as sns

In [ ]:
df = sns.load_dataset('tips')

In [ ]:
df.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [ ]:
df = df.drop(columns=['day'])

In [ ]:
df['sex'] = df['sex'].map({'Female':0,'Male':1})

In [ ]:
df['smoker'] = df['smoker'].map({'Yes':1,'No':0})
df['time'] = df['time'].map({'Dinner':1,'Lunch':0})

In [ ]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
time          0
size          0
dtype: int64

In [ ]:
x = df.drop(columns=['total_bill'])
y = df['total_bill']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=50)

In [ ]:
np.round(x_train.describe(),2)

          tip    size
count  195.00  195.00
mean     2.94    2.56
std      1.37    0.97
min      1.00    1.00
25%      2.00    2.00
50%      2.74    2.00
75%      3.50    3.00
max     10.00    6.00

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
mn = MinMaxScaler()

In [ ]:
x_train_mn = mn.fit_transform(x_train)

In [ ]:
x_train_new = pd.DataFrame(x_train_mn,columns=x_train.columns)

In [ ]:
np.round(x_train_new.describe(),2)

          tip     sex  smoker    time    size
count  195.00  195.00  195.00  195.00  195.00
mean     0.22    0.66    0.35    0.73    0.31
std      0.15    0.48    0.48    0.45    0.19
min      0.00    0.00    0.00    0.00    0.00
25%      0.11    0.00    0.00    0.00    0.20
50%      0.19    1.00    0.00    1.00    0.20
75%      0.28    1.00    1.00    1.00    0.40
max      1.00    1.00    1.00    1.00    1.00

**ENCODING**

In [ ]:
# Encoding ----> Transform your Categorical data into Numerical data
# (1). Label ----> It will encode data 1 by 1 columns.
# (2). Ordinal----> It will encode data on more than 1 column
# (3). OneHot----> It will create new column based on sub-categories but it has only values  not column names
# (4). get_dummies----> It will create new column based on sub - categories but is shows column names with values.

LabelEncoder

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/toyota - toyota.csv')

In [ ]:
df.head(2)

  model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0  GT86  2016  16000       Manual    24089   Petrol  265  36.2         2.0
1  GT86  2017  15995       Manual    18615   Petrol  145  36.2         2.0

In [ ]:
x = df.drop(columns=['price'])
y = df['price']

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb = LabelEncoder()

In [ ]:
x['model'] = lb.fit_transform(x['model'])
x['transmission'] = lb.fit_transform(x['transmission'])
x['fuelType'] = lb.fit_transform(x['fuelType'])

In [ ]:
x.head(3)

   model  year  transmission  mileage  fuelType  tax   mpg  engineSize
0      6  2016             1    24089         3  265  36.2         2.0
1      6  2017             1    18615         3  145  36.2         2.0
2      6  2015             1    27469         3  265  36.2         2.0

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
np.round(x_train.describe(),2)

,model,year,transmission,mileage,fuelType,tax,mpg,engineSize
count,5390.00,5390.00,5390.00,5390.00,5390.00,5390.0,5390.00,5390.00
mean,8.11,2016.75,0.68,22820.11,2.16,94.7,63.17,1.47
std,6.94,2.18,0.66,19104.20,1.09,73.9,16.16,0.44
min,0.00,1998.00,0.00,2.00,0.00,0.0,2.80,0.00
25%,2.00,2016.00,0.00,9500.00,1.00,0.0,55.40,1.00
50%,5.00,2017.00,1.00,18489.00,3.00,135.0,62.80,1.50
75%,17.00,2018.00,1.00,31057.00,3.00,145.0,69.00,1.80
max,17.00,2020.00,3.00,174419.00,3.00,565.0,235.00,4.50

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
x_train_sc = sc.fit_transform(x_train)

In [ ]:
x_train_new = pd.DataFrame(x_train_sc,columns=x_train.columns)

In [ ]:
np.round(x_train_new.describe(),2)

,model,year,transmission,mileage,fuelType,tax,mpg,engineSize
count,5390.00,5390.00,5390.00,5390.00,5390.00,5390.00,5390.00,5390.00
mean,0.00,-0.00,0.00,0.00,0.00,-0.00,0.00,-0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-1.17,-8.58,-1.03,-1.19,-1.99,-1.28,-3.74,-3.36
25%,-0.88,-0.34,-1.03,-0.70,-1.07,-1.28,-0.48,-1.07
50%,-0.45,0.12,0.49,-0.23,0.77,0.55,-0.02,0.07
75%,1.28,0.57,0.49,0.43,0.77,0.68,0.36,0.76
max,1.28,1.49,3.54,7.94,0.77,6.36,10.64,6.94

In [ ]:
df = pd.read_csv('/content/covid_toy.csv')

In [ ]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
x = df.drop(columns=['has_covid'])

In [ ]:
y = df['has_covid']

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb = LabelEncoder()

In [ ]:
x['gender'] = lb.fit_transform(x['gender'])
x['cough'] = lb.fit_transform(x['cough'])
x['city'] = lb.fit_transform(x['city'])

In [ ]:
x.head(2)

   age  gender  fever  cough  city
0   60       1  103.0      0     2
1   27       1  100.0      0     1

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=50)

In [ ]:
np.round(x_train.describe(),2)

         age  gender   fever  cough   city
count  80.00   80.00   71.00  80.00  80.00
mean   43.58    0.44  100.85   0.40   1.36
std    25.83    0.50    2.07   0.49   1.08
min     5.00    0.00   98.00   0.00   0.00
25%    20.00    0.00   99.00   0.00   0.00
50%    42.00    0.00  101.00   0.00   1.50
75%    66.50    1.00  102.00   1.00   2.00
max    84.00    1.00  104.00   1.00   3.00

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
x_train_sc = sc.fit_transform(x_train)

In [ ]:
x_train_new  = pd.DataFrame(x_train_sc,columns=x_train.columns)

In [ ]:
np.round(x_train_new.describe(),2)

         age  gender  fever  cough   city
count  80.00   80.00  71.00  80.00  80.00
mean   -0.00    0.00  -0.00  -0.00   0.00
std     1.01    1.01   1.01   1.01   1.01
min    -1.50   -0.88  -1.39  -0.82  -1.27
25%    -0.92   -0.88  -0.90  -0.82  -1.27
50%    -0.06   -0.88   0.08  -0.82   0.13
75%     0.89    1.13   0.56   1.22   0.59
max     1.57    1.13   1.54   1.22   1.52

Ordinal Encoder

In [ ]:
df=pd.read_csv('/content/covid_toy.csv')

In [ ]:
df=df.dropna()

In [ ]:
df=df.drop(columns=['age','fever'])

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder(categories=[['Male','Female'],
                                ['Mild','Strong'],
                                ['Kolkata','Bangalore','Delhi','Mumbai'],
                                ['Yes','No']])

In [ ]:
df_ar = oe.fit_transform(df)

In [ ]:
df_new = pd.DataFrame(df_ar, columns = df.columns)

In [ ]:
df_new

    gender  cough  city  has_covid
0      0.0    0.0   0.0        1.0
1      0.0    0.0   2.0        0.0
2      0.0    0.0   2.0        1.0
3      1.0    0.0   0.0        1.0
4      1.0    0.0   3.0        1.0
..     ...    ...   ...        ...
85     1.0    0.0   1.0        1.0
86     1.0    1.0   0.0        0.0
87     1.0    0.0   1.0        1.0
88     1.0    1.0   3.0        1.0
89     1.0    1.0   0.0        0.0

[90 rows x 4 columns]

ONE HOT ENCODING

In [ ]:
# columns has_covid['y','n']----> new column y_has_covid , n_has_covid----> but contain only value not column names

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/covid_toy.csv')
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
df = df.dropna()

In [ ]:
df = df.drop(columns=['age','fever'])

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe = OneHotEncoder(drop = 'first',sparse_output = False,dtype = np.int32)

In [ ]:
# gender --> 2-1=1
# cough --> 2-1=1
# city --> 4-1=3
# has_covid --> 2-1=1

In [ ]:
ohe.fit_transform(df[['gender','cough','city','has_covid']])

array([[1, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 1],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [1, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 1],
       [0, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0],
       [1, 1, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 1],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 1],
       [1, 0, 0, 1, 0, 0],
       [0, 1, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 1],
       [1, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0],
       [1, 0, 1, 0, 0, 1],
       [0, 1, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1],
       [1, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 1, 1],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1],
       [0, 1, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [1, 1, 0, 1, 0, 1],
       [0, 1, 1, 0, 0, 0],
       [1, 0, 0, 1, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 1, 1],
       [1, 0, 1, 0, 0, 0],
       [1, 0, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [1, 1, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0],
       [0, 1, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 1]], dtype=int32)

get_dummies

In [ ]:
a = pd.get_dummies(df, columns=['gender','cough','city','has_covid'],drop_first=True)

In [ ]:
a = a.astype(int)

In [ ]:
df = pd.read_csv('/content/toyota - toyota.csv')
df.head(2)

  model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0  GT86  2016  16000       Manual    24089   Petrol  265  36.2         2.0
1  GT86  2017  15995       Manual    18615   Petrol  145  36.2         2.0

In [ ]:
df = df.dropna()

In [ ]:
df = df.drop(columns=['year'])

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe = OneHotEncoder(drop = 'first',sparse_output = False, dtype = np.int32)

In [ ]:
ohe.fit_transform(df[['fuelType','model','transmission']])

array([[0, 0, 1, ..., 1, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [0, 0, 1, ..., 1, 0, 0]], dtype=int32)

In [ ]:
a = pd.get_dummies(df, columns=['fuelType','model','transmission'],drop_first=True)

In [ ]:
a = a.astype(int)

In [ ]:
a

,price,mileage,tax,mpg,engineSize,fuelType_Hybrid,fuelType_Other,fuelType_Petrol,model_Avensis,model_Aygo,...,model_Prius,model_RAV4,model_Supra,model_Urban Cruiser,model_Verso,model_Verso-S,model_Yaris,transmission_Manual,transmission_Other,transmission_Semi-Auto
0,16000,24089,265,36,2,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
1,15995,18615,145,36,2,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,13998,27469,265,36,2,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
3,18998,14736,150,36,2,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
4,17498,36284,145,36,2,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6733,5500,30000,20,58,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
6734,4985,36154,125,50,1,0,0,1,0,0,...,0,0,0,1,0,0,0,1,0,0
6735,4995,46000,125,57,1,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
6736,3995,60700,125,50,1,0,0,1,0,0,...,0,0,0,1,0,0,0,1,0,0
6737,4495,45128,125,50,1,0,0,1,0,0,...,0,0,0,1,0,0,0,1,0,0

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
df.head()

  model  price transmission  mileage fuelType  tax   mpg  engineSize
0  GT86  16000       Manual    24089   Petrol  265  36.2         2.0
1  GT86  15995       Manual    18615   Petrol  145  36.2         2.0
2  GT86  13998       Manual    27469   Petrol  265  36.2         2.0
3  GT86  18998       Manual    14736   Petrol  150  36.2         2.0
4  GT86  17498       Manual    36284   Petrol  145  36.2         2.0

In [ ]:
lb = LabelEncoder()

In [ ]:
df['model'] = lb.fit_transform(df['model'])

In [ ]:
df['transmission'] = lb.fit_transform(df['transmission'])

In [ ]:
df['fuelType'] = lb.fit_transform(df['fuelType'])

In [ ]:
df.head()

   model  price  transmission  mileage  fuelType  tax   mpg  engineSize
0      6  16000             1    24089         3  265  36.2         2.0
1      6  15995             1    18615         3  145  36.2         2.0
2      6  13998             1    27469         3  265  36.2         2.0
3      6  18998             1    14736         3  150  36.2         2.0
4      6  17498             1    36284         3  145  36.2         2.0

In [ ]:
df2 = pd.read_csv('/content/toyota - toyota.csv')

In [ ]:
df2.head(2)

  model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0  GT86  2016  16000       Manual    24089   Petrol  265  36.2         2.0
1  GT86  2017  15995       Manual    18615   Petrol  145  36.2         2.0

In [ ]:
df2 = df2.dropna()

In [ ]:
df2['fuelType'].value_counts()

fuelType
Petrol    4087
Hybrid    2043
Diesel     503
Other      105
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
df2['model'] = lb.fit_transform(df['model'])

In [ ]:
df2 = df2.drop(columns=['model','year','price','mileage','tax','mpg','engineSize'])

In [ ]:
df2

     transmission fuelType
0          Manual   Petrol
1          Manual   Petrol
2          Manual   Petrol
3          Manual   Petrol
4          Manual   Petrol
...           ...      ...
6733    Automatic   Petrol
6734       Manual   Petrol
6735       Manual   Diesel
6736       Manual   Petrol
6737       Manual   Petrol

[6738 rows x 2 columns]

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder(categories=[['Manual','Automatic','Semi-Auto','Other'],['Petrol','Hybrid','Diesel','Other']])

In [ ]:
df_ar = oe.fit_transform(df2)

In [ ]:
df_new = pd.DataFrame(df_ar,columns=df2.columns)

In [ ]:
df_new.head()

   transmission  fuelType
0           0.0       0.0
1           0.0       0.0
2           0.0       0.0
3           0.0       0.0
4           0.0       0.0

In [ ]:
import seaborn as sns

In [ ]:
tips = sns.load_dataset('tips')

In [ ]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
tips.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [ ]:
a = pd.get_dummies(tips,columns=['sex','smoker','day','time'],drop_first=True)

In [ ]:
a = a.astype(int)

In [ ]:
a

,total_bill,tip,size,sex_Female,smoker_No,day_Fri,day_Sat,day_Sun,time_Dinner
0,16,1,2,1,1,0,0,1,1
1,10,1,3,0,1,0,0,1,1
2,21,3,3,0,1,0,0,1,1
3,23,3,2,0,1,0,0,1,1
4,24,3,4,1,1,0,0,1,1
...,...,...,...,...,...,...,...,...,...
239,29,5,3,0,1,0,1,0,1
240,27,2,2,1,0,0,1,0,1
241,22,2,2,0,0,0,1,0,1
242,17,1,2,0,1,0,1,0,1
243,18,3,2,1,1,0,0,0,1

In [ ]:
x = a.drop(columns=['total_bill'])
y = a['total_bill']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=50)

In [ ]:
np.round(x_train.describe(),2)

,tip,size,sex_Female,smoker_No,day_Fri,day_Sat,day_Sun,time_Dinner
count,195.00,195.00,195.00,195.00,195.00,195.00,195.00,195.00
mean,2.66,2.56,0.34,0.65,0.08,0.33,0.34,0.73
std,1.41,0.97,0.48,0.48,0.28,0.47,0.48,0.45
min,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,2.00,2.00,0.00,0.00,0.00,0.00,0.00,0.00
50%,2.00,2.00,0.00,1.00,0.00,0.00,0.00,1.00
75%,3.00,3.00,1.00,1.00,0.00,1.00,1.00,1.00
max,10.00,6.00,1.00,1.00,1.00,1.00,1.00,1.00

In [ ]:
x_train.head(10)

     tip  size  sex_Female  smoker_No  day_Fri  day_Sat  day_Sun  time_Dinner
8      1     2           0          1        0        0        1            1
232    3     2           0          1        0        1        0            1
186    3     3           1          0        0        0        1            1
162    2     3           1          1        0        0        1            1
144    2     2           1          1        0        0        0            0
123    2     2           0          1        0        0        0            0
138    2     2           0          0        0        0        0            0
12     1     2           0          1        0        0        1            1
112    4     3           0          1        0        0        1            1
102    2     3           1          0        0        1        0            1

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
mn = MinMaxScaler()

In [ ]:
x_train_mn = mn.fit_transform(x_train)

In [ ]:
x_train_new = pd.DataFrame(x_train_mn,columns=x_train.columns)

In [ ]:
np.round(x_train_new.describe(),2)

,tip,size,sex_Female,smoker_No,day_Fri,day_Sat,day_Sun,time_Dinner
count,195.00,195.00,195.00,195.00,195.00,195.00,195.00,195.00
mean,0.18,0.31,0.34,0.65,0.08,0.33,0.34,0.73
std,0.16,0.19,0.48,0.48,0.28,0.47,0.48,0.45
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.11,0.20,0.00,0.00,0.00,0.00,0.00,0.00
50%,0.11,0.20,0.00,1.00,0.00,0.00,0.00,1.00
75%,0.22,0.40,1.00,1.00,0.00,1.00,1.00,1.00
max,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/Churn_Modelling - Churn_Modelling.csv')

In [ ]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

Label Encoder

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb = LabelEncoder()

In [ ]:
df = df.drop(columns=['Surname'])

In [ ]:
df['Geography'] = lb.fit_transform(df['Geography'])
df['Gender'] = lb.fit_transform(df['Gender'])

In [ ]:
df.head()

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,0,0,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,2,0,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,0,0,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,0,0,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,2,0,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
b = pd.read_csv('/content/Churn_Modelling - Churn_Modelling.csv')

In [ ]:
b.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
b = b.drop(columns=['Surname'])

In [ ]:
cat_b = b[['Geography','Gender']]
num_b = b.drop(columns=['Geography','Gender'])

In [ ]:
cat_b['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

Ordinal Encoder

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder(categories=[['France','Germany','Spain'],['Female','Male']])

In [ ]:
catt_b=oe.fit_transform(cat_b)

In [ ]:
cat_b = pd.DataFrame(catt_b,columns=cat_b.columns)

In [ ]:
cat_b = cat_b.astype(int)
cat_b

      Geography  Gender
0             0       0
1             2       0
2             0       0
3             0       0
4             2       0
...         ...     ...
9995          0       1
9996          0       1
9997          0       0
9998          1       1
9999          0       0

[10000 rows x 2 columns]

In [ ]:
df = pd.concat([num_b, cat_b], axis=1)

In [ ]:
df

,RowNumber,CustomerId,Surname,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,1,15634602,Hargrave,619,42,2,0.00,1,1,1,101348.88,1,0,0,0
1,2,15647311,Hill,608,41,1,83807.86,1,0,1,112542.58,0,0,1,0
2,3,15619304,Onio,502,42,8,159660.80,3,1,0,113931.57,1,0,0,0
3,4,15701354,Boni,699,39,1,0.00,2,0,0,93826.63,0,0,0,0
4,5,15737888,Mitchell,850,43,2,125510.82,1,1,1,79084.10,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,39,5,0.00,2,1,0,96270.64,0,0,0,1
9996,9997,15569892,Johnstone,516,35,10,57369.61,1,1,1,101699.77,0,0,0,1
9997,9998,15584532,Liu,709,36,7,0.00,1,0,1,42085.58,1,0,0,0
9998,9999,15682355,Sabbatini,772,42,3,75075.31,2,1,0,92888.52,1,1,0,1
9999,10000,15628319,Walker,792,28,4,130142.79,1,1,0,38190.78,0,0,0,0

Column Transformer

In [1]:
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [2]:
df = pd.read_csv('/content/covid_toy.csv')

In [3]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [6]:
x_train

    age  gender  fever   cough       city
21   73    Male   98.0    Mild  Bangalore
34   74    Male  102.0    Mild     Mumbai
77    8  Female  101.0    Mild    Kolkata
8    19  Female  100.0  Strong  Bangalore
86   25    Male  104.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
53   83    Male   98.0    Mild      Delhi
96   51  Female  101.0  Strong    Kolkata
85   16  Female  103.0    Mild  Bangalore
19   42  Female    NaN  Strong  Bangalore
70   68  Female  101.0  Strong      Delhi

[80 rows x 5 columns]

In [7]:
from sklearn.impute import SimpleImputer
# adding simple imputer to fever column
si = SimpleImputer(strategy='mean')
x_train_fever = si.fit_transform(x_train[['fever']])

# also the test data
x_test_fever = si.fit_transform(x_test[['fever']])

x_train_fever.shape

(80, 1)

In [9]:
# Ordinal Encoding ----> cough

oe = OrdinalEncoder(categories = [['Mild','Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])

# also the test data
x_test_cough = oe.fit_transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

In [11]:
# OneHotEncoding ---> Gender, city

ohe = OneHotEncoder(drop = 'first',sparse_output = False)
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])

#also the test data
x_test_gender_city = ohe.fit_transform(x_test[['gender','city']])

x_train_gender_city.shape

(80, 4)

In [13]:
# Extracting Age

x_train_age = x_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
x_test_age = x_test.drop(columns=['gender','fever','cough','city']).values

In [14]:
x_train_age.shape

(80, 1)

In [16]:
x_train_transform = np.concatenate((x_train_age,x_train_fever,
                                    x_train_gender_city,
                                    x_train_cough),axis=1)

In [17]:
x_train_transform.shape

(80, 7)

**By the help of column transformer**

In [22]:
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']), # in a 'fever column by the help of SI we fill missing values by mean, median, mode.
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']), #by this process we encode our data.
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
    ],remainder='passthrough') # remainder = passthrough ==> It means rest of all the columns remain same

In [23]:
transformer.fit_transform(x_train).shape

(80, 7)

In [24]:
transformer.transform(x_test).shape

(20, 7)

In [35]:
import seaborn as sns
tips = sns.load_dataset('tips')

In [36]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [37]:
tips.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [38]:
tips = tips.drop(columns=['day'])

In [39]:
x_train,x_test,y_train,y_test = train_test_split(tips.drop(columns=['total_bill']),tips['total_bill'],test_size=0.2,random_state=50)

In [40]:
x_train

      tip     sex smoker    time  size
8    1.96    Male     No  Dinner     2
232  3.39    Male     No  Dinner     2
186  3.50  Female    Yes  Dinner     3
162  2.00  Female     No  Dinner     3
144  2.30  Female     No   Lunch     2
..    ...     ...    ...     ...   ...
33   2.45  Female     No  Dinner     4
109  4.00  Female    Yes  Dinner     2
139  2.75  Female     No   Lunch     2
224  1.58    Male    Yes   Lunch     2
176  2.00    Male    Yes  Dinner     2

[195 rows x 5 columns]

In [41]:
oe = OrdinalEncoder(categories=[['Male','Female']])
x_train_sex = oe.fit_transform(x_train[['sex']])

In [42]:
x_test_sex = oe.fit_transform(x_test[['sex']])

In [43]:
x_train_sex.shape

(195, 1)

In [44]:
ohe = OneHotEncoder(drop='first',sparse_output=False)

x_train_smoker_time = ohe.fit_transform(x_train[['smoker','time']])

x_test_smoker_time = ohe.fit_transform(x_test[['smoker','time']])

x_train_smoker_time.shape

(195, 2)

In [45]:
# Extracting tip

x_train_tip = x_train.drop(columns=['smoker','sex','time','size']).values

x_test_tip = x_test.drop(columns=['smoker','sex','time','size']).values

In [46]:
# Extracting Size

x_train_size = x_train.drop(columns=['smoker','tip','sex','time']).values

x_test_size = x_test.drop(columns=['smoker','tip','sex','time']).values

In [47]:
x_train_transform = np.concatenate((x_train_sex,x_train_smoker_time,x_train_tip,x_train_size),axis=1)

In [48]:
x_train_transform.shape

(195, 5)

By column transformer

In [50]:
from sklearn.compose import ColumnTransformer

In [56]:
transform = ColumnTransformer(transformers=[
    ('tnf1',OrdinalEncoder(categories=[['Male','Female'],['Yes','No'],['Dinner','Lunch']]),['sex','smoker','time'],)
],remainder='passthrough')

In [57]:
transform.fit_transform(x_train).shape

(195, 5)

In [59]:
transform.transform(x_test).shape

(49, 5)