In [ ]:
# Intoduction to pandas
# pandas is an open-source library of python which is used for handling data mainpulations.

In [ ]:
#!pip install pandas

In [ ]:
import pandas as pd

In [ ]:
# Data structure of pandas
# (1). Series
# (2). DataFrame

In [ ]:
# 1. Series ---> It is one-dimensional array and it retuns only values.

In [ ]:
se = pd.Series([1,45,32,23,8,28])
se

0     1
1    45
2    32
3    23
4     8
5    28
dtype: int64

In [ ]:
type(se)

pandas.core.series.Series

In [ ]:
# 2. DataFrame ---> It is multi-dimensional array and it returns data in rows and columns.

In [ ]:
# We have to create a dataframe of employees in which columns are
# emp_id,emp_name,department,salary,working_hours

In [ ]:
dict = {'Emp_id':[101,102,103,104],
        'Emp_name':['Amit','Ashok','Priya','Priyanka'],
        'Department':['IT','Operations','IT','Operations'],
        'Salary':[50000,65000,55000,60000],
        'Working_hours':[9,8,9,8]}

In [ ]:
df = pd.DataFrame(dict)
df

   Emp_id  Emp_name  Department  Salary  Working_hours
0     101      Amit          IT   50000              9
1     102     Ashok  Operations   65000              8
2     103     Priya          IT   55000              9
3     104  Priyanka  Operations   60000              8

In [ ]:
# How can we export our dataframe into csv

In [ ]:
df.to_csv('emp_info.csv') # to_csv means export your data into csv

In [ ]:
df.to_csv('new_emp_info.csv',index=False) # index=False means it will remove unnamed column.

In [ ]:
df = pd.read_csv('/content/flipkart.csv')

In [ ]:
df

,Model Name,Model Name.1,Model Name.2,Model Name.3,Model Name.4,Model Name.5,Model Name.6,Model Name.7,Model Name.8
0,"OnePlus Nord 5 5G (Dry Ice, 256 GB)",895 Ratings,74 Reviews,12 GB RAM | 256 GB ROM,17.35 cm (6.83 inch) Display,50MP Rear Camera,6800 mAh Battery,1 Year Warranty,NaN
1,"OnePlus 13R 5G (Nebula Noir, 512 GB)","1,666 Ratings",108 Reviews,16 GB RAM | 512 GB ROM,17.22 cm (6.78 inch) Display,50MP Rear Camera,6000 mAh Battery,1 year manufacturer warranty for device and 1 ...,NaN
2,"OnePlus 13R 5G (Nebula Noir, 256 GB)","3,967 Ratings",262 Reviews,12 GB RAM | 256 GB ROM,17.22 cm (6.78 inch) Display,50MP Rear Camera,6000 mAh Battery,1 year manufacturer warranty for device and 1 ...,NaN
3,"OnePlus 13R 5g (Astral Trail, 256 GB)","3,967 Ratings",262 Reviews,12 GB RAM | 256 GB ROM,17.22 cm (6.78 inch) Display,50MP Rear Camera,6000 mAh Battery,1 year manufacturer warranty for device and 1 ...,NaN
4,"OnePlus Nord 5 5G (Phantom Grey, 512 GB)",895 Ratings,74 Reviews,12 GB RAM | 512 GB ROM,17.35 cm (6.83 inch) Display,50MP Rear Camera,6800 mAh Battery,1 Year Warranty,NaN
5,"IQOO Neo 10 (Titanium Chrome, 512 GB)",117 Ratings,5 Reviews,16 GB RAM | 512 GB ROM,17.22 cm (6.78 inch) Full HD+ E3 Super AMOLED ...,50MP + 50MP + 8MP | 32MP + 32MP Dual Front Camera,7000 mAh Battery,Qualcomm Processor,NaN
6,"Samsung Galaxy A55 5G (Awesome Iceblue, 256 GB)",619 Ratings,46 Reviews,12 GB RAM | 256 GB ROM | Expandable Upto 1 TB,16.76 cm (6.6 inch) Full HD+ Display,50MP + 12MP + 5MP | 32MP Front Camera,5000 mAh Battery,Exynos 1480 Processor,NaN
7,"MOTOROLA Razr 60 (PANTONE Spring Bud, 256 GB)","1,684 Ratings",122 Reviews,8 GB RAM | 256 GB ROM,17.53 cm (6.9 inch) Full HD+ Display,50MP + 13MP | 32MP Front Camera,4500 mAh Battery,Dimensity 7400X Processor,NaN
8,"OnePlus Nord 5 5G (Marble Sands, 256 GB)",895 Ratings,74 Reviews,12 GB RAM | 256 GB ROM,17.35 cm (6.83 inch) Display,50MP Rear Camera,6800 mAh Battery,1 Year Warranty,NaN
9,"Xiaomi 14 CIVI (Aqua Blue, 512 GB)","1,022 Ratings",100 Reviews,12 GB RAM | 512 GB ROM,16.64 cm (6.55 inch) Display,50MP Rear Camera | 32MP + 32MP Dual Front Camera,4700 mAh Battery,8s Gen 3 Mobile Platform Processor,NaN
10,"vivo V30 Pro 5G (Classic Black, 256 GB)","7,407 Ratings",863 Reviews,8 GB RAM | 256 GB ROM,17.22 cm (6.78 inch) Full HD+ Display,50MP + 50MP + 50MP | 50MP Front Camera,5000 mAh Battery,Dimensity 8200 5G Processor,NaN
11,"OnePlus Nord 5 5G (Phantom Grey, 256 GB)",895 Ratings,74 Reviews,12 GB RAM | 256 GB ROM,17.35 cm (6.83 inch) Display,50MP Rear Camera,6800 mAh Battery,1 Year Warranty,NaN
12,"Apple iPhone 14 (Starlight, 128 GB)","3,19,722 Ratings","11,867 Reviews",128 GB ROM,15.49 cm (6.1 inch) Super Retina XDR Display,12MP + 12MP | 12MP Front Camera,"A15 Bionic Chip, 6 Core Processor Processor",1 year warranty for phone and 1 year warranty ...,NaN
13,"Apple iPhone 14 (Midnight, 128 GB)","3,19,722 Ratings","11,867 Reviews",128 GB ROM,15.49 cm (6.1 inch) Super Retina XDR Display,12MP + 12MP | 12MP Front Camera,"A15 Bionic Chip, 6 Core Processor Processor",1 year warranty for phone and 1 year warranty ...,NaN
14,"Motorola Edge 50 Ultra 5G (Nordic Wood, 512 GB)","3,184 Ratings",335 Reviews,12 GB RAM | 512 GB ROM,17.02 cm (6.7 inch) Display,50MP + 50MP + 64MP | 50MP Front Camera,4500 mAh Battery,8s Gen 3 Mobile Platform Processor,NaN
15,"vivo V40 Pro 5G (Ganges Blue, 512 GB)","1,129 Ratings",118 Reviews,12 GB RAM | 512 GB ROM,17.22 cm (6.78 inch) Full HD+ Display,50MP + 50MP + 50MP | 50MP Front Camera,5500 mAh Battery,Dimensity 9200+ Processor,NaN
16,"Google Pixel 7 (Lemongrass, 128 GB)","19,868 Ratings","2,141 Reviews",8 GB RAM | 128 GB ROM,16.0 cm (6.3 inch) Full HD+ Display,50MP + 12MP | 10.8MP Front Camera,4270 mAh Battery,Google Tensor G2 Processor,NaN
17,"vivo V30 Pro 5G (Andaman Blue, 256 GB)","7,407 Ratings",863 Reviews,8 GB RAM | 256 GB ROM,17.22 cm (6.78 inch) Full HD+ Display,50MP + 50MP + 50MP | 50MP Front Camera,5000 mAh Battery,Dimensity 8200 5G Processor,NaN
18,"Samsung Galaxy A36 5G (Awesome Lavender, 256 GB)",240 Ratings,14 Reviews,12 GB RAM | 256 GB ROM,17.02 cm (6.7 inch) Full HD+ Display,50MP + 8MP | 12MP Front Camera,5000 mAh Battery,Qualcomm Snapdragon 6 Gen 3 Processor,NaN
19,"Samsung Galaxy S23 5G (Phantom Black, 128 GB)","80,994 Ratings","5,434 Reviews",8 GB RAM | 128 GB ROM,15.49 cm (6.1 inch) Full HD+ Display,50MP + 10MP + 12MP | 12MP Front Camera,3900 mAh Lithium Ion Battery,Qualcomm Snapdragon 8 Gen 2 Processor,NaN
20,"Xiaomi 14 CIVI (Hot Pink, 512 GB)","1,022 Ratings",100 Reviews,12 GB RAM | 512 GB ROM,16.64 cm (6.55 inch) Display,50MP Rear Camera | 32MP + 32MP Dual Front Camera,4700 mAh Battery,8s Gen 3 Mobile Platform Processor,NaN
21,"Apple iPhone 13 (Starlight, 128 GB)","2,94,713 Ratings","13,992 Reviews",128 GB ROM,15.49 cm (6.1 inch) Super Retina XDR Display,12MP + 12MP | 12MP Front Camera,A15 Bionic Chip Processor,1 year warranty for phone and 1 year warranty ...,NaN
22,"vivo X80 (Cosmic Black, 128 GB)","1,059 Ratings",178 Reviews,8 GB RAM | 128 GB ROM,17.22 cm (6.78 inch) Full HD+ Display,50MP + 12MP + 12MP | 32MP Front Camera,4500 mAh Lithium Battery,Mediatek Dimensity 9000 Processor,NaN
23,"Samsung Galaxy S23 5G (Green, 256 GB)","80,994 Ratings","5,434 Reviews",8 GB RAM | 256 GB ROM,15.49 cm (6.1 inch) Full HD+ Display,50MP + 10MP + 12MP | 12MP Front Camera,3900 mAh Lithium Ion Battery,Qualcomm Snapdragon 8 Gen 2 Processor,NaN

In [ ]:
df = pd.read_csv('/content/Best restaurants in jaipur.csv')

In [ ]:
df

,Restaurant name,Type of restaurant,Ratings,Address
0,Skyfall Restaurant,· · Restaurant,4.3,"5th Floor, Ridhi Tower, SB 57, Tonk Rd, opposi..."
1,Suvarna Mahal,· · North Indian,4.7,"RAMBAGH PALACE, Bhawani Singh Rd"
2,Peacock Restaurant,· · North Indian,4.4,Rajasthan
3,NaN,NaN,NaN,NaN
4,Govindam Retreat,· · Restaurant,4.4,"First Floor, All Rajasthan Shilp Gram Udyog, B..."
5,Handi restaurant jaipur,· · Restaurant,4.1,"Mirza Ismail Rd, opp. GPO"
6,J Brew & Kitchen Rooftop Restaurant,· North Indian,4.7,"97 A, 5, Bhawani Singh Ln, near News 18 Channel"
7,The Forresta Kitchen & Bar,· · Brewpub,4.2,"Devraj Niwas, Mirza Ismail Rd, near Khasa Koth..."
8,Rustic - Inspired Kitchen,· North Indian,4.8,"G-3, Ground Floor, UKMS, AURUM, Tilak Marg"
9,Stardust Jaipur,· · North Indian,4.2,"Terrace floor, Signature Tower, Tonk Rd"
10,Nouba Restaurant & Rooftop Lounge,· Restaurant,4.5,"3rd and 4th floor, Rooftop, C54-A, Sarojini Marg"
11,The DeIicious Yard // family restaurants in ja...,· · Restaurant,4.7,"3, Panchawati Colony, Plot No.- 2, in front of..."
12,Topaz & Sangria,· North Indian,4.6,"Hotel Natraj, Ganpati Plaza, Motilal Atal Rd"
13,Sura - Cocktails & Cuisine,· Restaurant,4.9,"Hathroi Fort, 5th Floor, Ajmer Rd, inside Hote..."
14,Brewlicious Rooftop Bar Restaurant in Jaipur,· · North Indian,4.8,"10th floor, Gadi, Okay Plus Tower, 5, Ajmer Rd..."
15,Dyore Restaurant & Lounge Experience,· Restaurant,4.3,"16, Parivahan Marg"
16,The Lama,· · Pan Asian,4.7,"145, Ramesh Marg, above OTH E"
17,Townsend - Bar & Kitchen,· · Grill,4.4,Moti Doongri Rd
18,Hawk View Restaurant & Bar,· · Biryani,4.3,"76, Raja Mal Ka Talab, behind Kale Hanuman Ji ..."
19,Shikaar Bagh - Restaurant and Bar,· · North Indian,4.3,Hotel Narain Niwas Palace
20,Meraaki Kitchen,· · Indian,4.4,"Near Civil Lines Metro Station Piller No. 88, ..."

In [ ]:
df = pd.read_csv('/content/flipkart shoes.csv')

In [ ]:
df

,Brand,Description,Discounted Price,Actual Price,Discount
0,Asics,GEL-CUMULUS 26 Running Shoes For Men,"₹5,163","₹10,999",53% off
1,Asics,GT-1000 LE 2 (2E) Running Shoes For Men,"₹4,799","₹9,999",52% off
2,New Balance,327 Sneakers For Men,"₹4,800","₹9,999",51% off
3,New Balance,997R Sneakers For Men,"₹5,760","₹11,999",51% off
4,Asics,HYPER SPEED 5 Running Shoes For Men,"₹4,319","₹8,999",52% off
5,Asics,GT-1000 13 Running Shoes For Men,"₹4,799","₹9,999",52% off
6,Skechers,327 Sneakers For Men,"₹4,199","₹6,999",40% off
7,Skechers,Skechers Mens D'Lux Walker-Commuter Casual Lac...,"₹4,499","₹7,499",40% off
8,SAUCONY,PROGRID TRIUMPH 4 Sneakers For Men,"₹5,577","₹14,299",60% off
9,Asics,GEL-PULSE 16 Running Shoes For Men,"₹4,319","₹8,999",52% off

In [ ]:
df = pd.read_csv('/content/Top 10 places in mussorie.csv')
df

                        Place  Ratings Reviews      Best known for
0                   Cloud end      4.5  (4.3K)  Tourist attraction
1       Lal Tibba Scenic Cafe      4.1   (19K)         Scenic spot
2       Atal Udhyan Mussoorie      4.2  (6.3K)                Park
3        George Everest House      4.5  (9.6K)         Observatory
4                Bhatta falls      4.3  (8.5K)  Tourist attraction
5            Camels Back Road      NaN     NaN               Route
6         Gun Hill, Mussoorie      4.0   (11K)  Tourist attraction
7                   Mall Road      4.4  (1.3K)      Notable street
8                     Landour      NaN     NaN        Sublocality1
9               Christ Church      4.3    -406              Church
10             Mussoorie Lake      3.8    -556  Tourist attraction
11   Benog Wildlife Sanctuary      4.4    -195       Wildlife park
12        Chardukan Mussoorie      4.3  (7.2K)           Fast Food
13        Mussoorie Mall Road      4.5    -550  Tourist attraction
14     SOHAM Himalayan Centre      4.6    -253              Museum
15    Kellogg Memorial Church      4.5    -595              Church
16               Kempty Falls      4.2   (59K)  Tourist attraction
17               Happy Valley      NaN     NaN        Sublocality2
18    Tibetan Buddhist Temple      4.6  (2.7K)     Buddhist temple
19  Mussoorie Heritage Centre      4.5     -52              Museum

In [ ]:
df = pd.read_csv('/content/covid_toy.csv')

In [ ]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [ ]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df.tail()

    age  gender  fever   cough       city has_covid
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

In [ ]:
df.columns

Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='object')

In [ ]:
df.sample(2)

    age  gender  fever   cough       city has_covid
87   47    Male  101.0  Strong  Bangalore        No
26   19  Female  100.0    Mild    Kolkata       Yes

In [ ]:
df.dtypes

age            int64
gender        object
fever        float64
cough         object
city          object
has_covid     object
dtype: object

In [ ]:
df.describe()

              age       fever
count  100.000000   90.000000
mean    44.220000  100.844444
std     24.878931    2.054926
min      5.000000   98.000000
25%     20.000000   99.000000
50%     45.000000  101.000000
75%     66.500000  102.750000
max     84.000000  104.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    object
 2   fever      90 non-null     float64
 3   cough      100 non-null    object
 4   city       100 non-null    object
 5   has_covid  100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
df['fever'].mean()

np.float64(100.84444444444445)

In [ ]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [ ]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [ ]:
df = pd.read_csv('/content/placement - placement.csv')
df

    cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [ ]:
df.head()

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [ ]:
df.tail()

    cgpa  resume_score  placed
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

In [ ]:
df.sample()

    cgpa  resume_score  placed
38   6.0          8.72       0

In [ ]:
df.describe()

           cgpa  resume_score      placed
count  100.0000    100.000000  100.000000
mean     6.9422      6.930500    0.500000
std      1.1192      0.979608    0.502519
min      5.2700      4.950000    0.000000
25%      5.9800      6.190000    0.000000
50%      6.6200      7.055000    0.500000
75%      8.0450      7.640000    1.000000
max      9.4000      9.060000    1.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cgpa          100 non-null    float64
 1   resume_score  100 non-null    float64
 2   placed        100 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

In [ ]:
top_left_corner_df = df.iloc[:4,:3]    # iloc[row_range , column_range]
top_left_corner_df                     # it excludes the last value in range and only take range in numerical

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1

In [ ]:
df.loc[1:3 , ['cgpa','placed']]  # loc[row_range,column_range]
# it includes all values and accept range in both numerical and categorial

   cgpa  placed
1  6.17       0
2  8.27       1
3  6.88       1

In [ ]:
s = df.axes
s

[RangeIndex(start=0, stop=100, step=1),
 Index(['cgpa', 'resume_score', 'placed'], dtype='object')]

In [ ]:
p = df.dtypes
p

cgpa            float64
resume_score    float64
placed            int64
dtype: object

In [ ]:
b = df.empty # it returns True if there is any missing value in the dataset
b

False

In [ ]:
df.isnull().sum() # it tells how many null values are present

cgpa            0
resume_score    0
placed          0
dtype: int64

In [ ]:
df = df.dropna() # it delets the row in which null values are present

In [ ]:
df.ndim

2

In [ ]:
print(df.shape)
print(df.shape[0])  # total rows in data
print(df.shape[1])  # total columns in data

(100, 3)
100
3

In [ ]:
df.size

300

In [ ]:
df.values

array([[8.14, 6.52, 1.  ],
       [6.17, 5.17, 0.  ],
       [8.27, 8.86, 1.  ],
       [6.88, 7.27, 1.  ],
       [7.52, 7.3 , 1.  ],
       [8.77, 6.19, 1.  ],
       [5.34, 7.09, 0.  ],
       [6.56, 6.29, 0.  ],
       [6.32, 6.71, 0.  ],
       [7.69, 7.12, 1.  ],
       [6.18, 6.35, 0.  ],
       [5.44, 6.54, 0.  ],
       [6.09, 7.01, 0.  ],
       [8.5 , 5.09, 1.  ],
       [7.51, 6.25, 1.  ],
       [8.88, 5.93, 1.  ],
       [8.04, 7.64, 1.  ],
       [7.81, 8.71, 1.  ],
       [5.94, 5.88, 0.  ],
       [6.75, 8.11, 1.  ],
       [5.8 , 8.06, 0.  ],
       [6.53, 7.64, 0.  ],
       [6.16, 5.77, 0.  ],
       [6.05, 7.13, 0.  ],
       [8.22, 6.18, 1.  ],
       [7.76, 5.68, 1.  ],
       [6.27, 6.47, 0.  ],
       [5.51, 6.15, 0.  ],
       [7.46, 7.67, 1.  ],
       [6.19, 7.3 , 0.  ],
       [7.36, 7.15, 1.  ],
       [5.92, 7.02, 0.  ],
       [5.87, 7.96, 0.  ],
       [8.43, 7.73, 1.  ],
       [8.87, 7.19, 1.  ],
       [8.07, 7.48, 1.  ],
       [8.16, 7.56, 1.  ],
       [9.05, 8.21, 1.  ],
       [6.  , 8.72, 0.  ],
       [7.5 , 6.19, 1.  ],
       [8.25, 5.32, 1.  ],
       [8.68, 5.15, 1.  ],
       [6.9 , 6.91, 1.  ],
       [8.21, 7.95, 1.  ],
       [5.47, 5.92, 0.  ],
       [8.1 , 5.44, 1.  ],
       [5.83, 5.21, 0.  ],
       [7.05, 8.14, 1.  ],
       [5.54, 6.57, 0.  ],
       [5.46, 6.73, 0.  ],
       [8.22, 6.74, 1.  ],
       [6.54, 7.39, 0.  ],
       [5.9 , 7.5 , 0.  ],
       [6.  , 7.16, 0.  ],
       [5.92, 7.18, 0.  ],
       [6.94, 6.87, 1.  ],
       [6.13, 6.43, 0.  ],
       [6.34, 7.21, 0.  ],
       [6.47, 7.37, 0.  ],
       [5.95, 7.57, 0.  ],
       [5.87, 6.64, 0.  ],
       [6.89, 7.96, 1.  ],
       [5.75, 8.43, 0.  ],
       [8.65, 7.58, 1.  ],
       [7.93, 8.09, 1.  ],
       [6.04, 8.75, 0.  ],
       [8.35, 8.02, 1.  ],
       [6.59, 6.81, 1.  ],
       [6.01, 7.49, 0.  ],
       [8.06, 9.06, 1.  ],
       [7.12, 7.41, 1.  ],
       [7.34, 8.22, 1.  ],
       [7.63, 7.98, 1.  ],
       [5.76, 6.48, 0.  ],
       [5.54, 7.36, 0.  ],
       [6.34, 7.94, 1.  ],
       [9.4 , 5.5 , 1.  ],
       [5.88, 6.92, 0.  ],
       [5.79, 5.66, 0.  ],
       [5.27, 7.28, 0.  ],
       [7.83, 7.7 , 1.  ],
       [6.12, 6.72, 0.  ],
       [7.92, 6.06, 1.  ],
       [7.6 , 8.08, 1.  ],
       [5.76, 6.49, 0.  ],
       [6.72, 5.46, 0.  ],
       [6.18, 5.76, 0.  ],
       [5.62, 5.05, 0.  ],
       [8.07, 6.07, 1.  ],
       [5.99, 7.49, 0.  ],
       [5.85, 5.56, 0.  ],
       [8.28, 6.3 , 1.  ],
       [5.43, 6.18, 0.  ],
       [9.31, 7.39, 1.  ],
       [8.01, 4.95, 1.  ],
       [6.33, 6.38, 0.  ],
       [8.23, 7.76, 1.  ],
       [6.65, 7.78, 0.  ],
       [8.14, 5.63, 1.  ],
       [6.09, 6.61, 0.  ]])

In [ ]:
df = df.copy()

In [ ]:
p = df.sort_values(by = 'resume_score')    # by default ascending order
p

    cgpa  resume_score  placed
94  8.01          4.95       1
87  5.62          5.05       0
13  8.50          5.09       1
41  8.68          5.15       1
1   6.17          5.17       0
..   ...           ...     ...
17  7.81          8.71       1
38  6.00          8.72       0
65  6.04          8.75       0
2   8.27          8.86       1
69  8.06          9.06       1

[100 rows x 3 columns]

In [ ]:
p = df.sort_values(by = 'resume_score',ascending=False)   # descending order
p

   cgpa  resume_score  placed
69    8          9.06       1
2     8          8.86       1
65    6          8.75       0
38    6          8.72       0
17    7          8.71       1
..  ...           ...     ...
1     6          5.17       0
41    8          5.15       1
13    8          5.09       1
87    5          5.05       0
94    8          4.95       1

[100 rows x 3 columns]

In [ ]:
r = df.sort_index()
r

    cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [ ]:
df['cgpa'] = df['cgpa'].astype(int)

In [ ]:
df.head()

   cgpa  resume_score  placed
0     8          6.52       1
1     6          5.17       0
2     8          8.86       1
3     6          7.27       1
4     7          7.30       1

In [ ]:
df['cgpa'] = df['cgpa'].astype(str)

In [ ]:
df.dtypes

cgpa             object
resume_score    float64
placed            int64
dtype: object

In [ ]:
df['resume_score'] = df['resume_score'].astype(int)

In [ ]:
df.dtypes

cgpa            object
resume_score     int64
placed           int64
dtype: object

In [ ]:
df['resume_score'] = df['resume_score'].add(5)

In [ ]:
df.head()

  cgpa  resume_score  placed
0    8            11       1
1    6            10       0
2    8            13       1
3    6            12       1
4    7            12       1

In [ ]:
df.count()  # It counts the values a column contain

cgpa            100
resume_score    100
placed          100
dtype: int64

In [ ]:
df.max()  # It returns the maximum value in a column

cgpa             9
resume_score    14
placed           1
dtype: object

In [ ]:
df.min()  # It retuns the minimum value in a column

cgpa            5
resume_score    9
placed          0
dtype: object

In [ ]:
g = df.filter(items=['cgpa','placed'])
g

# df[['cgpa','placed']] -->  Second option of filtering

   cgpa  placed
0     8       1
1     6       0
2     8       1
3     6       1
4     7       1
..  ...     ...
95    6       0
96    8       1
97    6       0
98    8       1
99    6       0

[100 rows x 2 columns]

In [ ]:
s = df.filter(items=[5,6] , axis=0)  # In pandas axis = 0  means row wise operation
s

  cgpa  resume_score  placed
5    8            11       1
6    5            12       0

In [ ]:
t = df.filter(like='5',axis=0)
t

   cgpa  resume_score  placed
5     8            11       1
15    8            10       1
25    7            10       1
35    8            12       1
45    8            10       1
50    8            11       1
51    6            12       0
52    5            12       0
53    6            12       0
54    5            12       0
55    6            11       1
56    6            11       0
57    6            12       0
58    6            12       0
59    5            12       0
65    6            13       0
75    6            12       1
85    6            10       0
95    6            11       0

In [ ]:
p = df.rename(columns = {'cgpa':'updated_cgpa' , 'resume_score':'semester_marks'})
p

   updated_cgpa  semester_marks  placed
0             8              11       1
1             6              10       0
2             8              13       1
3             6              12       1
4             7              12       1
..          ...             ...     ...
95            6              11       0
96            8              12       1
97            6              12       0
98            8              10       1
99            6              11       0

[100 rows x 3 columns]

In [ ]:
df['half'] = df['resume_score'].where(df['resume_score']>11,other=0)
df.head(5)

  cgpa  resume_score  placed  half
0    8            11       1     0
1    6            10       0     0
2    8            13       1    13
3    6            12       1    12
4    7            12       1    12

In [ ]:
df.groupby('placed').size()

placed
0    50
1    50
dtype: int64